version: '4.2'
services:
  eureka-server:
    container_name: eureka
    image: eureka-server #nombre de la imagen que hemos creado
    restart: always
    ports:
      - '8761:8761'
    networks:
      - tfg-network

  user-service:
    container_name: user_microservice
    image: user-service #nombre de la imagen que hemos creado
    build: .
    ports:
      - '8082:8082'
    depends_on:
      - postgres_db
    networks:
      - tfg-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_microservice_db:5432/users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  review-microservice:
    container_name: review_microservice
    image: review-microservice
    build: .
    ports:
      - '8084:8084'
    depends_on:
      - postgres_db
    networks:
      - tfg-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://review_microservice_db:5432/reviews
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  search-microservice:
    container_name: search_microservice
    image: search-microservice
    build: .
    ports:
      - '8083:8083'
    depends_on:
      - postgres_db
    networks:
      - tfg-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://review_microservice_db:5432/search
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  gateway-service:
    container_name: gateway_service
    image: gateway-service
    build: .
    ports:
      - '8081:8081'
    networks:
      - tfg-network

  postgres_db:
    container_name: user_microservice_db
    image: postgres:15
    ports:
      - '5432:5432'
    networks:
      - tfg-network
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    networks:
      - 'tfg-network'
    depends_on:
      - postgres_db
networks:
  tfg-network:
    driver: bridge
